name: verify

on: push

jobs:
  oj-verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        pip3 install -U online-judge-verify-helper
    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all --jobs 2
    - name: Push snippets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MY_GITHUB_ACTION_TEST : 1
        CPP_JSON_GIST_TOKEN : ${{ secrets.CPP_JSON_GIST_TOKEN }}
        CPP_JSON_GIST_ID : ${{ secrets.CPP_JSON_GIST_ID }}
      run: |
          git checkout master
          cd .github/myscript
          ./push_snippets.sh
          cd ../../