name: verify

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -U setuptools
        pip3 install -U online-judge-tools=='6.*'
    - name: test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MY_GITHUB_ACTION_TEST : 1
        OJ_TEST_RECENT_FILES_COUNT : 1
      run: ./test/test.sh
