name: verify

on: push

jobs:
  # oj-verify-atcoder-environment:
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v1

  #   - name: Set up Python
  #     uses: actions/setup-python@v1

  #   - name: Install dependencies
  #     run: |
  #       pip3 install -U online-judge-verify-helper
  #       sudo apt-get install g++-5
  #   - name: Run tests
  #     env:
  #       CXX: g++-5
  #     run: env GITHUB_REF="" oj-verify run --jobs 2

  oj-verify:
    # needs: oj-verify-atcoder-environment
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        pip3 install -U online-judge-verify-helper
    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all --jobs 2

  push-snippet:
    needs: oj-verify
    runs-on: ubuntu-18.04
    steps:
    - name: push-snippet
      uses: spihill/push-snippet-action@master
      with:
        YOUR_GITHUB_USER_NAME: 'spihill'
        YOUR_GITHUB_REPOSITORY: 'library'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SNIPPET_GIST_TOKEN : ${{ secrets.CPP_JSON_GIST_TOKEN }}
        SNIPPET_GIST_ID : ${{ secrets.CPP_JSON_GIST_ID }}
        SNIPPET_FILE_NAME : 'cpp.json'
        SNIPPET_IGNORE_FILE_PATH: 'verify/:.test.cpp:test/:develop/:for_include'