name: verify

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -U setuptools
        pip3 install -U online-judge-tools=='7.*'
    - name: change_timestamp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MY_GITHUB_ACTION_TEST : 1
        CPP_JSON_GIST_TOKEN : ${{ secrets.CPP_JSON_GIST_TOKEN }}
        TIMESTAMP_GIST_ID : ${{ secrets.TIMESTAMP_GIST_ID }}
      run: |
          cd .github/myscript
          ./change_timestamp.sh
          cd ../../
    - name: test
      env:
        MY_GITHUB_ACTION_TEST : 1
        OJ_TEST_RECENT_FILES_COUNT : 100
      run: ./test/test.sh
    - name: update_timestamp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MY_GITHUB_ACTION_TEST : 1
        CPP_JSON_GIST_TOKEN : ${{ secrets.CPP_JSON_GIST_TOKEN }}
        TIMESTAMP_GIST_ID : ${{ secrets.TIMESTAMP_GIST_ID }}
      run: |
          cd .github/myscript
          ./update_timestamp.sh
          cd ../../
    - name: push_snippets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MY_GITHUB_ACTION_TEST : 1
        CPP_JSON_GIST_TOKEN : ${{ secrets.CPP_JSON_GIST_TOKEN }}
        CPP_JSON_GIST_ID : ${{ secrets.CPP_JSON_GIST_ID }}
      run: |
          cd .github/myscript
          ./push_snippets.sh
          cd ../../
