name: verify

on:
  push:
    branches:
      - master

jobs:
  oj-verify:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper
    - name: Run tests
      run: oj-verify run --jobs 2
    - name: upload timestamp
      uses: actions/upload-artifact@v1
      with:
        name: .verify-helper
        path: .verify-helper/timestamps.remote.json

  oj-verify-gcc-5.5.0:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        pip3 install -U online-judge-verify-helper
        sudo apt-get install g++-5
    - name: Run tests
      env:
        CXX: g++-5
      run: oj-verify run --jobs 2

  oj-verify-publish:
    needs: [oj-verify, oj-verify-atcoder-environment]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: checkout to master
      run: git checkout master
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        pip3 install -U online-judge-verify-helper
    - name: remove timestamp
      run: rm -rf .verify-helper
    - name: download timestamp
      uses: actions/download-artifact@v1
      with:
        name: .verify-helper
    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all --jobs 2

  push-snippet:
    needs: [oj-verify, oj-verify-atcoder-environment]
    runs-on: ubuntu-18.04
    steps:
    - name: push-snippet
      uses: spihill/push-snippet-action@v1.2
      with:
        YOUR_GITHUB_USER_NAME: 'spihill'
        YOUR_GITHUB_REPOSITORY: 'library'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SNIPPET_GIST_TOKEN : ${{ secrets.CPP_JSON_GIST_TOKEN }}
        SNIPPET_GIST_ID : ${{ secrets.CPP_JSON_GIST_ID }}
        SNIPPET_FILE_NAME : 'cpp.json'
        SNIPPET_IGNORE_FILE_PATH: 'verify/:.test.cpp:test/:develop/:for_include'
